"""Constants definitions"""


exchange_map = {
    "XNYM": "New York Mercantile Exchange",
    "XCME": "Chicago Mercantile Exchange",
    "XCEC": "Commodities Exchange Center",
    "XCBT": "Chicago Board of Trade",
}
underlying_product_map = {
    2: "Commodity/Agriculture",
    4: "Currency",
    5: "Equity",
    6: "Government",
    10: "Mortgage",
    12: "Other",
    13: "Financing",
    14: "Interest Rate",
    15: "FX Cash",
    16: "Energy",
    17: "Metals",
}
security_type_map = {
    "FUT": "Future",
    "OOF": "Option on Future",
    "MLEG": "Spread with mixed type leg",
    "IRS": "Interest Rate Swap",
    "FXSPOT": "FX Spot",
    "TBOND": "US Treasury Bond",
    "TBILL": "US Treasury Bill",
    "TB": "Non-US Treasury Bill",
    "TBA": "To Be Announced",
    "SOV": "UK Gilts",
    "EUSOV": "Euro Government Bonds",
    "EUSUP": "Euro Supranational",
    "SUPRA": "US Supranational",
    "REPO": "REPO Instruments",
    "TIPS": "Treasury Inflation-Protected Securities",
    "TINT": "US Treasury STRIPS",
}
unit_of_measure_map = {
    "ALLOW": "Allowances",
    "AUD": "Australian Dollar",
    "BBL": "Blue Barrel (42-gallon oil barrel)",
    "BDFT": "Board Feet",
    "BRL": "Brazilian Real",
    "BU": "Bushel",
    "CAD": "Canadian Dollar",
    "CBM": "Cubic Meters",
    "CHF": "Swiss Franc",
    "CLP": "Chilean Peso",
    "CRT": "Climate Reserve Tonnes",
    "CTRCT": "Contract",
    "CWT": "Hundred Weight",
    "CZK": "Czech Koruna",
    "DT": "Dry Metric Tons",
    "ENVCRD": "Environmental Credit",
    "ENVOFST": "Environmental Offset",
    "EUR": "Euro",
    "GAL": "Gallons",
    "GBP": "Pounds Sterling (British Pounds)",
    "GRAMS": "Grams",
    "GT": "Gross Tons",
    "HUF": "Hungarian Forint",
    "ILS": "Israeli Shekel",
    "INR": "Indian Rupee",
    "IPNT": "Index Points",
    "JPY": "Japanese Yen",
    "KG": "Kilograms",
    "KL": "Kilolitres",
    "KRW": "Korean Won",
    "LBS": "Pounds",
    "MTONS": "Metric Tons",
    "MMBTU": "One Million British Thermal Units",
    "MWH": "Megawatts Per Hour",
    "MXN": "Mexican Peso",
    "MYR": "Malaysian Ringgit",
    "NOK": "Norwegian Kroner",
    "NZD": "New Zealand Dollar",
    "PLN": "Polish Zloty",
    "RCER": "Certified Emission Reduction credit",
    "RIN": "Renewable Identification Number",
    "RMB": "Chinese Renminbi",
    "RUB": "Russian Ruble",
    "SEK": "Swedish Kronor",
    "THM": "Therm",
    "TONS": "Tons",
    "TRY": "Turkish Lira",
    "TRYOZ": "Troy Ounce",
    "USD": "U.S. Dollar",
    "ZAR": "South African Rand",
    "WMT": "Wet Metric Ton"
}

currencies = [
    "AUD", "BRL", "CAD", "CHF", "CLP", "CZK", "JPY", "EUR", "HUF", "GBP", "KRW", "MXN", "MYR", "NOK", "NZD",
    "PLN", "RMB", "RUB", "SEK", "TRY", "USD", "ZAR", "INR", "ILS",
]

measurements = [
    "BBL",
    "BDFT",
    "BU",
    "CBM",
    "CRT",
    "DT",
    "GAL",
    "GRAMS",
    "GT",
    "KG",
    "KL",
    "LBS",
    "MTONS",
    "MMBTU",
    "MWH",
    "THM",
    "TONS",
    "TRYOZ",
    "WMT",
]

supported_units = {
    "currency": [
        {"id": d, "name": d, "description": unit_of_measure_map[d]}
        for d in currencies
    ],
    "measurement": [
        {"id": d, "name": d, "description": unit_of_measure_map[d]}
        for d in measurements
    ],
    "other": [
        {"id": d, "name": d, "description": unit_of_measure_map[d]}
        for d in list(unit_of_measure_map)
        if d not in currencies and d not in measurements
    ],
}

live_grid_assets = [
    "BTC",
    "BTE",
    "BFF",
    "RX",
    "XAZ",
    "XAY",
    "XAP",
    "YM",
    "XAE",
    "FT1",
    "FT5",
    "DVE",
    "EI",
    "XAF",
    "XAV",
    "IPO",
    "XAI",
    "XAB",
    "QCN",
    "BIO",
    "NQ",
    "ENY",
    "SOX",
    "RSG",
    "RS1",
    "RSV",
    "R2G",
    "RTY",
    "R2V",
    "EWF",
    "ES",
    "SMC",
    "SXT",
    "E3G",
    "SXI",
    "EMD",
    "SXO",
    "SXB",
    "SXR",
    "XAK",
    "FTU",
    "XAU",
    "ETE",
    "ETH",
    "EBR",
    "EBM",
    "MBT",
    "MYM",
    "MNQ",
    "M2K",
    "MES",
    "MMC",
    "MSC",
    "EEM",
    "MET",
    "MNI",
    "MNK",
    "MSL",
    "H2O",
    "NDA",
    "NKD",
    "NIY",
    "RDA",
    "SDA",
    "SG",
    "SDI",
    "SU",
    "SOL",
    "TPD",
    "IBV",
    "TPY",
    "6A",
    "ACD",
    "AJY",
    "ANE",
    "6L",
    "6B",
    "PJY",
    "PSF",
    "6C",
    "CJY",
    "CHP",
    "RME",
    "RMB",
    "CZK",
    "ECK",
    "E7",
    "J7",
    "ENZ",
    "6E",
    "EAD",
    "RP",
    "ECD",
    "RY",
    "ENK",
    "ESK",
    "RF",
    "PAD",
    "PCD",
    "PNK",
    "PSK",
    "HUF",
    "EHF",
    "SIR",
    "ILS",
    "6J",
    "KRW",
    "6M",
    "M6A",
    "MCD",
    "MSF",
    "M6E",
    "M6B",
    "MIR",
    "MJY",
    "NSK",
    "NZC",
    "NJY",
    "6N",
    "NOK",
    "PLN",
    "EPZ",
    "6R",
    "6Z",
    "CNH",
    "SEK",
    "6S",
    "SJY",
    "TRL",
    "ZN",
    "10Y",
    "ZT",
    "2YY",
    "TWE",
    "Z3N",
    "ZQ",
    "20U",
    "25U",
    "30U",
    "35U",
    "40U",
    "45U",
    "50U",
    "55U",
    "60U",
    "65U",
    "30Y",
    "ZF",
    "5YY",
    "HYB",
    "DHY",
    "IQB",
    "DHB",
    "ESR",
    "XEU",
    "FFV",
    "TIE",
    "MTN",
    "MWN",
    "MGE",
    "SR1",
    "SON",
    "RFD",
    "RFI",
    "SR3",
    "TBF3",
    "ZB",
    "TN",
    "UB",
    "MBA",
    "AA4",
    "A9N",
    "A7E",
    "V7",
    "BPA",
    "BB",
    "CY",
    "BZ",
    "ACU",
    "CC3",
    "GEO",
    "NGO",
    "MTF",
    "A8L",
    "A8M",
    "CPP",
    "A8K",
    "WS",
    "CL",
    "RN3",
    "RN4",
    "RN6",
    "GBR",
    "C3D",
    "C5D",
    "C4D",
    "DCL",
    "TTE",
    "TFU",
    "TTD",
    "QM",
    "QH",
    "QG",
    "QU",
    "AA5",
    "JE",
    "EMC",
    "AI2",
    "AI1",
    "EAA",
    "YHE",
    "AI6",
    "AI5",
    "ERL",
    "EAC",
    "AJ1",
    "AI9",
    "EAB",
    "YUE",
    "AO1",
    "AN1",
    "YWK",
    "YWE",
    "NA2",
    "BEF",
    "AGX",
    "APS",
    "ECF",
    "FBD",
    "FLJ",
    "FLP",
    "TF2",
    "FRS",
    "FRC",
    "T5C",
    "T7C",
    "T8C",
    "TM",
    "TC6",
    "T2D",
    "ACB",
    "AEB",
    "TL",
    "TK",
    "TD8",
    "B7H",
    "GNO",
    "GES",
    "GSW",
    "LNG",
    "LBU",
    "UCO",
    "AJ",
    "AUS",
    "HPE",
    "NG",
    "NN",
    "NPG",
    "HHW",
    "JCC",
    "JCY",
    "JBK",
    "JPK",
    "JBT",
    "JPT",
    "LPE",
    "AXA",
    "BL1",
    "BL2",
    "BL3",
    "ALX",
    "MH",
    "LL",
    "MQA",
    "AQA",
    "MX",
    "MO",
    "CMS",
    "MTH",
    "MT2",
    "MNG",
    "MHO",
    "MRB",
    "MCL",
    "MAS",
    "MAE",
    "MBC",
    "MPS",
    "T4D",
    "TMD",
    "T2M",
    "TLD",
    "MEO",
    "MAA",
    "AC0",
    "MBR",
    "A8I",
    "MBL",
    "B0",
    "A81",
    "A7Q",
    "AD0",
    "TEF",
    "MNB",
    "A3Q",
    "3L",
    "A3N",
    "A3R",
    "3P",
    "A3M",
    "MBE",
    "ABH",
    "MPX",
    "HO",
    "5Y",
    "HH",
    "HP",
    "HHT",
    "PGG",
    "PDJ",
    "SDD",
    "SRT",
    "PPP",
    "A1R",
    "NA3",
    "RT",
    "RLX",
    "RB",
    "RGF",
    "RBF",
    "RGI",
    "UCS",
    "NBP",
    "NBD",
    "CSX",
    "HIA",
    "HTA",
    "AXB",
    "WTI",
    "TCS",
    "ABY",
    "BK",
    "AY",
    "1OZ",
    "EDP",
    "AEP",
    "ALI",
    "BCH",
    "COH",
    "COB",
    "HGS",
    "HG",
    "HGF",
    "CUP",
    "QC",
    "QO",
    "QI",
    "4GC",
    "GC",
    "TIO",
    "LED",
    "LTH",
    "MHG",
    "MGC",
    "PAM",
    "PLM",
    "SIL",
    "EHR",
    "PA",
    "PL",
    "SGC",
    "SGU",
    "SI",
    "SPM",
    "BUS",
    "HDG",
    "UX",
    "ZNC",
    "BLK",
    "AW",
    "DRS",
    "CWR",
    "CSC",
    "CB",
    "ZW",
    "DC",
    "GDK",
    "CJ",
    "KT",
    "ZC",
    "TT",
    "DFN",
    "DY",
    "GF",
    "KE",
    "HE",
    "LE",
    "LBR",
    "MFC",
    "MZC",
    "MZS",
    "MZM",
    "MZL",
    "MZW",
    "XK",
    "XC",
    "MKC",
    "XW",
    "YO",
    "GNF",
    "ZO",
    "PRK",
    "ZR",
    "GD",
    "GIE",
    "ZS",
    "ZM",
    "ZL",
    "OSF",
    "HR",
    "UNO",
    "CPV",
    "UFB",
    "UFE",
    "UME",
    "UFV",
]
